version: "3.8"

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  image: custom-airflow:2.7.1-python3.9
  env_file:
    - airflow.env
  volumes:
    - ./config:/opt/airflow/config
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./etls:/opt/airflow/etls
    - ./logs:/opt/airflow/logs
    - ./pipelines:/opt/airflow/pipelines
    - ./plugins:/opt/airflow/plugins
    - ./tests:/opt/airflow/tests
    - ./utils:/opt/airflow/utils
    - ./requirements.txt:/opt/airflow/requirements.txt
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_started

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow_reddit
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d airflow_reddit"]
      interval: 5s
      timeout: 5s
      retries: 10
    dns:
      - 8.8.8.8
      - 8.8.4.4

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
      pip install -r /opt/airflow/requirements.txt &&
      airflow db init &&
      airflow users create \
        --username admin \
        --firstname admin \
        --lastname admin \
        --role Admin \
        --email airflow@airflow.com \
        --password admin
      "
    restart: "no"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  airflow-webserver:
    <<: *airflow-common
    command: airflow webserver
    ports:
      - "8081:8080"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  airflow-scheduler:
    <<: *airflow-common
    command: airflow scheduler
    dns:
      - 8.8.8.8
      - 8.8.4.4

  airflow-worker:
    <<: *airflow-common
    command: airflow celery worker
    dns:
      - 8.8.8.8
      - 8.8.4.4
